"""Generate per-track landing pages (e.g. /singleplayergames/) from index.html.

Each page is the full site, but opens with that track loaded as the featured track and has its own
title / canonical / share card. Re-run after editing index.html:  python tools/make-feature-pages.py
"""
import json, os, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = 'https://www.geartogetyoufolded.llc'

PAGES = [
    {'slug': 'singleplayergames', 'track': 'single-player-games', 'og': 'og-spg-v1.jpg',
     'desc': 'Single Player Games by zero (exfilcamper01): dark, sinister riddim. Headphones on.'},
]

js = open(os.path.join(ROOT, 'assets/data/tracks.js'), encoding='utf8').read()
tracks = json.loads(js[js.index('window.TRACKS=') + 14: js.rindex(';')])
base = open(os.path.join(ROOT, 'index.html'), encoding='utf8').read()
home = tracks[0]

def sub(s, a, b):
    if a not in s: raise SystemExit(f'pattern not found: {a[:70]}')
    return s.replace(a, b)

for p in PAGES:
    t = next(x for x in tracks if x['id'] == p['track'])
    url = f"{SITE}/{p['slug']}"
    s = base
    s = re.sub(r'<title>[^<]*</title>', f"<title>{t['title']} — exfilcamper01</title>", s, count=1)
    s = re.sub(r'<meta name="description" content="[^"]*">', f'<meta name="description" content="{p["desc"]}">', s, count=1)
    s = sub(s, f'<link rel="canonical" href="{SITE}/">', f'<link rel="canonical" href="{url}">')
    s = sub(s, f'<meta property="og:url" content="{SITE}/">', f'<meta property="og:url" content="{url}">')
    s = re.sub(r'(property="og:title" content=")[^"]*', rf'\1exfilcamper01 — {t["title"]}', s)
    s = re.sub(r'(name="twitter:title" content=")[^"]*', rf'\1exfilcamper01 — {t["title"]}', s)
    s = re.sub(r'(property="og:description" content=")[^"]*', rf'\1{p["desc"]}', s)
    s = re.sub(r'(property="og:image:alt" content=")[^"]*', rf'\1exfilcamper01 — {t["title"]}, play on geartogetyoufolded.llc', s)
    s = re.sub(r'/assets/img/og-v\d+\.jpg', f"/assets/img/{p['og']}", s)
    # featured track: body flag (read by app.js), first-paint text, and the SoundCloud widget source
    s = sub(s, '<body class="is-gated">', f'<body class="is-gated" data-feature="{t["id"]}">')
    s = sub(s, f'src="{home["art"]}" alt="Artwork for {home["title"]}"', f'src="{t["art"]}" alt="Artwork for {t["title"]}"')
    s = sub(s, f'data-text="{home["title"]}">{home["title"]}</h2>', f'data-text="{t["title"]}">{t["title"]}</h2>')
    s = re.sub(r'(<p class="raid-credit" id="now-credit">)[^<]*', rf'\g<1>{t["credit"]}', s, count=1)
    s = sub(s, f'<span class="deck-now" id="deck-now">{home["title"]}</span>', f'<span class="deck-now" id="deck-now">{t["title"]}</span>')
    s = sub(s, f'<b id="extract-track">{home["title"]}</b>', f'<b id="extract-track">{t["title"]}</b>')
    s = sub(s, f'api.soundcloud.com/tracks/{home["scId"]}', f'api.soundcloud.com/tracks/{t["scId"]}')
    s = s.replace('<!-- generated -->', '')
    s = s.replace('<head>', '<head>\n<!-- GENERATED by tools/make-feature-pages.py from index.html; edit index.html and re-run -->', 1)
    os.makedirs(os.path.join(ROOT, p['slug']), exist_ok=True)
    open(os.path.join(ROOT, p['slug'], 'index.html'), 'w', encoding='utf8').write(s)
    print('wrote', p['slug'] + '/index.html')
